BASE:
- ''
TOOLBOX_MODE: unsupervised_method
UNSUPERVISED:
  EXP_PROCESS: true
  METHOD:
  - POS_WANG
  - ICA
  - CHROM
  - GREEN
  - LGI
  - PBV
  - OMIT
  METRICS:
  - MAE
  - RMSE
  - MAPE
  - Pearson
  - SNR
  DATA:
    FS: 30
    DATASET: COHFACE
    DO_PREPROCESS: True
    DATA_FORMAT: NDHWC
    DATA_PATH: /home/jupiter/rppg_dataset/cohface
    CACHED_PATH: ./PreprocessedData
    EXP_DATA_NAME: ''
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE:
      - Raw
      DATA_AUG:
      - None
      LABEL_TYPE: Raw
      DO_CHUNK: false
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: true
        BACKEND: HC
        USE_LARGE_FACE_BOX: true
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: false
      RESIZE:
        H: 128
        W: 128
DO_HILBERT: false
DO_ORDER_BPF: 1
INFERENCE:
  EVALUATION_METHOD: FFT
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: false
    WINDOW_SIZE: 10
